---
- name: Extract Certs on Broker
  import_role:
    name: ssl
    tasks_from: export_certs_from_keystore_and_truststore.yml
  vars:
    truststore_storepass: "{{ kafka_broker_truststore_storepass }}"
    truststore_path: "{{ kafka_broker_truststore_path }}"
    keystore_storepass: "{{ kafka_broker_keystore_storepass }}"
    keystore_path: "{{ kafka_broker_keystore_path }}"
    ca_cert_path: "{{ kafka_broker_ca_cert_path }}"
    cert_path: "{{ kafka_broker_cert_path }}"
    key_path: "{{ kafka_broker_key_path }}"
  when:
    - ssl_provided_keystore_and_truststore|bool
    - ssl_client_authentication in ['required', 'requested']
  delegate_to: "{{ groups['kafka_broker'][0] }}"

- name: Get Kafka Cluster Id
  import_role:
    name: common
    tasks_from: rbac_setup.yml
  vars:
    copy_certs: false
  delegate_to: "{{ groups['kafka_broker'][0] }}"

- name: Delete temporary keys/certs when keystore and trustore is provided
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "{{ kafka_broker_ca_cert_path }}"
    - "{{ kafka_broker_cert_path }}"
    - "{{ kafka_broker_key_path }}"
  when:
    - ssl_provided_keystore_and_truststore|bool
    - ssl_client_authentication in ['required', 'requested']
  delegate_to: "{{ groups['kafka_broker'][0] }}"

- set_fact:
    send_client_cert: "{{ ssl_client_authentication in ['required', 'requested'] }}"

- name: Register Schema Registry Cluster
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/registry/clusters"
    method: POST
    validate_certs: false
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ authorization_token }}"
    client_cert: "{{ schema_registry_cert_path if send_client_cert else omit }}"
    client_key: "{{schema_registry_key_path if send_client_cert else omit}}"
    body_format: json
    body: >
      [
          {
              "clusterName": "{{schema_registry_cluster_name}}",
              "scope": {
                  "clusters": {
                      "kafka-cluster": "{{kafka_cluster_id}}",
                      "schema-registry-cluster": "{{schema_registry_final_properties['schema.registry.group.id']}}"
                  }
              },
              "hosts": [ {% for host in groups['schema_registry'] %}{% if loop.index > 1%},{% endif %}{ "host": "{{host}}", "port": {{schema_registry_listener_port}} }{% endfor %}
              ],
              "protocol": '{{schema_registry_http_protocol | upper}}'
          }
      ]
    status_code: 204
  run_once: true
  no_log: "{{mask_secrets|bool}}"
  register: output
  until: output.status == 204
  retries: "{{ mds_retries }}"
  delay: 10
