---
- name: Extract Certs on Broker
  import_role:
    name: ssl
    tasks_from: export_certs_from_keystore_and_truststore.yml
  vars:
    truststore_storepass: "{{ kafka_broker_truststore_storepass }}"
    truststore_path: "{{ kafka_broker_truststore_path }}"
    keystore_storepass: "{{ kafka_broker_keystore_storepass }}"
    keystore_path: "{{ kafka_broker_keystore_path }}"
    ca_cert_path: "{{ kafka_broker_ca_cert_path }}"
    cert_path: "{{ kafka_broker_cert_path }}"
    key_path: "{{ kafka_broker_key_path }}"
  when:
    - ssl_provided_keystore_and_truststore|bool
    - ssl_client_authentication in ['required', 'requested']
  delegate_to: "{{ groups['kafka_broker'][0] }}"

- name: Get Authorization Token for Super User
  import_role:
    name: common
    tasks_from: get_authorization_token.yml
  vars:
    oauth: "{{ oauth_enabled }}"
    oauth_user: "{{ oauth_superuser_client_id }}"
    oauth_password: "{{ oauth_superuser_client_password }}"
    ldap_user: "{{ mds_super_user }}"
    ldap_password: "{{ mds_super_user_password }}"
    client_cert: "{{ kafka_broker_cert_path }}"
    client_key: "{{ kafka_broker_key_path }}"
  when: rbac_enabled or oauth_enabled
  delegate_to: "{{ groups['kafka_broker'][0] }}"

- name: Delete temporary keys/certs when keystore and trustore is provided
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "{{ kafka_broker_ca_cert_path }}"
    - "{{ kafka_broker_cert_path }}"
    - "{{ kafka_broker_key_path }}"
  when:
    - ssl_provided_keystore_and_truststore|bool
    - ssl_client_authentication in ['required', 'requested']
  delegate_to: "{{ groups['kafka_broker'][0] }}"

- name: Check Kafka Connect Connector Topics
  assert:
    that: kafka_connect_connector_white_list != ""
    fail_msg: "Please provide Connector's Topics to produce/consume data in the inventory file."

- set_fact:
    send_client_cert: "{{ ssl_client_authentication in ['required', 'requested'] }}"

- name: Grant Connect User ResourceOwner role on White List Topics
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{connect_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ authorization_token }}"
    client_cert: "{{ kafka_connect_cert_path if send_client_cert|bool else omit }}"
    client_key: "{{ kafka_connect_key_path if send_client_cert|bool else omit }}"
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}"
            }
        },
        "resourcePatterns": [
          {
            "resourceType":"Topic",
            "name":"{{item}}",
            "patternType":"LITERAL"
          }
        ]
      }
    status_code: 204
  register: connect_mds_result
  until: connect_mds_result.status == 204
  retries: "{{ mds_retries }}"
  delay: 5
  loop: "{{kafka_connect_connector_white_list.split(',')}}"

- name: Grant Connect User ResourceOwner role on resourceType Subject in Schema Registry Cluster
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{connect_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ authorization_token }}"
    client_cert: "{{ kafka_connect_cert_path if send_client_cert|bool else omit }}"
    client_key: "{{ kafka_connect_key_path if send_client_cert|bool else omit }}"
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}",
            "schema-registry-cluster": "{{schema_registry_final_properties['schema.registry.group.id']}}"
            }
        },
        "resourcePatterns": [
          {
            "resourceType":"Subject",
            "name":"{{item}}-value",
            "patternType":"LITERAL"
          }
        ]
      }
    status_code: 204
  register: connect_mds_result
  until: connect_mds_result.status == 204
  retries: "{{ mds_retries }}"
  delay: 5
  loop: "{{kafka_connect_connector_white_list.split(',')}}"
  when: ("'schema_registry' in groups")

- name: Grant Connect User DeveloperRead role to Consumer group
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{connect_user}}/roles/DeveloperRead/bindings"
    method: POST
    validate_certs: false
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ authorization_token }}"
    client_cert: "{{ kafka_connect_cert_path if send_client_cert|bool else omit }}"
    client_key: "{{ kafka_connect_key_path if send_client_cert|bool else omit }}"
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}"
            }
        },
        "resourcePatterns": [
          {
            "resourceType":"Group",
            "name":"connect-",
            "patternType":"PREFIXED"
          }
        ]
      }
    status_code: 204
  register: connect_mds_result
  until: connect_mds_result.status == 204
  retries: "{{ mds_retries }}"
  delay: 5

- name: Grant Connect User ResourceOwner role for the Connector
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{connect_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ authorization_token }}"
    client_cert: "{{ kafka_connect_cert_path if send_client_cert|bool else omit }}"
    client_key: "{{ kafka_connect_key_path if send_client_cert|bool else omit }}"
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}",
            "connect-cluster": "{{kafka_connect_final_properties['group.id']}}"
            }
        },
        "resourcePatterns": [
          {
            "resourceType":"Connector",
            "name":"{{item.name}}",
            "patternType":"LITERAL"
          }
        ]
      }
    status_code: 204
  register: connect_mds_result
  until: connect_mds_result.status == 204
  retries: "{{ mds_retries }}"
  delay: 5
  loop: "{{kafka_connect_connectors}}"
