---
- name: Extract Certs on Broker
  import_role:
    name: ssl
    tasks_from: export_certs_from_keystore_and_truststore.yml
  vars:
    truststore_storepass: "{{ kafka_broker_truststore_storepass }}"
    truststore_path: "{{ kafka_broker_truststore_path }}"
    keystore_storepass: "{{ kafka_broker_keystore_storepass }}"
    keystore_path: "{{ kafka_broker_keystore_path }}"
    ca_cert_path: "{{ kafka_broker_ca_cert_path }}"
    cert_path: "{{ kafka_broker_cert_path }}"
    key_path: "{{ kafka_broker_key_path }}"
  when:
    - ssl_provided_keystore_and_truststore|bool
    - ssl_client_authentication in ['required', 'requested']
  delegate_to: "{{ groups['kafka_broker'][0] }}"

- name: Get Kafka Cluster Id
  import_role:
    name: common
    tasks_from: rbac_setup.yml
  vars:
    copy_certs: false
  delegate_to: "{{ groups['kafka_broker'][0] }}"

- name: Delete temporary keys/certs when keystore and trustore is provided
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "{{ kafka_broker_ca_cert_path }}"
    - "{{ kafka_broker_cert_path }}"
    - "{{ kafka_broker_key_path }}"
  when:
    - ssl_provided_keystore_and_truststore|bool
    - ssl_client_authentication in ['required', 'requested']
  delegate_to: "{{ groups['kafka_broker'][0] }}"

- name: Register Kafka Replicator Cluster
  uri:
    url: "{{kafka_connect_replicator_erp_host.split(',')[0]| default('localhost:8090')}}/security/1.0/registry/clusters"
    method: POST
    validate_certs: false
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ authorization_token }}"
    client_cert: "{{ kafka_connect_replicator_cert_path }}"
    client_key: "{{ kafka_connect_replicator_key_path }}"
    body_format: json
    body: >
      [
          {
              "clusterName": "{{kafka_connect_replicator_cluster_name}}",
              "scope": {
                  "clusters": {
                      "kafka-cluster": "{{kafka_cluster_id}}",
                      "connect-cluster": "{{kafka_connect_replicator_final_properties['group.id']}}"
                  }
              },
              "hosts": [ {% for host in groups['kafka_connect_replicator'] %}{% if loop.index > 1%},{% endif %}{ "host": "{{host}}", "port": {{kafka_connect_replicator_port}} }{% endfor %}
              ],
              "protocol": "{{kafka_connect_replicator_http_protocol | upper}}"
          }
      ]
    status_code: 204
  run_once: true
  register: output
  until: output.status == 204
  retries: 20
  delay: 10
